Update docker-compose.yml
my network was not getting started when I was using this repo and when I cloned the repo from https://gerrit.hyperledger.org/r/admin/repos/fabric-samples then i was able to resolve my issue mentioned below

# Create the channel
docker exec -e "CORE_PEER_LOCALMSPID=Org1MSP" -e "CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.example.com/msp" peer0.org1.example.com peer channel create -o orderer.example.com:7050 -c mychannel -f /etc/hyperledger/configtx/channel.tx
2019-07-11 08:59:08.309 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Error: got unexpected status: FORBIDDEN -- implicit policy evaluation failed - 0 sub-policies were satisfied, but this policy requires 1 of the 'Writers' sub-policies to be satisfied: permission denied

one of the major diff I have found that with new git clone cli had downloaded new images for couchdb 2.3 and that the reason I have updated this config file from image: hyperledger/fabric-couchdb to image: couchdb:2.3